### ISSUE TITLE
Consistent users don't see enough of their old entries

### ISSUE THREAD

**Issue by r00k** [codecation/trailmix#154]
If there someone has an entry from exactly one week, one month, or one year ago, we include that entry in their prompt. (Otherwise we pick at random.)

[Here's the code](https://github.com/codecation/trailmix/blob/master/app/models/prompt_entry.rb#L12).

Users who write every day will actually never see entries older than a week.

Even at my frequency (2-5 times a week) I rarely see my entries older than a year. This is a shame since I have many years of entries and sometimes the oldest ones are the most interesting.

Potential fixes:
* Make the choice more random.
* Make the choice totally random! I know we had an explicit request to show entries from exactly one year ago, but do we actually prefer this to random? I'm not convinced.

**Comment by mblayman** [comment]
I recognize that I'm a comment from the peanut gallery, but I would be in favor of being totally random. I dug into the code trying to understand why my entries kept coming from 7 days ago, and then went to the issues page to report this existing issue. I'm glad you beat me to it! :smile: IMO, getting an old entry from exactly 365 days ago is not much more interesting than getting one from, say, 370 days ago. In other words, the interesting heuristic of year/month/week doesn't matter much to me.

I signed up for Trailmix because of this line on your landing copy:

> With every reminder email, **we'll include one of your previous entries chosen at random**.

Later in the copy, there's this:

> Before you know it, you're a daily journaler.

The ironic part is that being a daily journaler like I am effectively makes random seem like:

```ruby
def random
  # ¯\_(ツ)_/¯
  7
end
```

I hope I don't sound rant-y. I'm really appreciative of the service, and it has helped me journal even on the days when I don't want to. The random feature is what keeps me, a persistent user, coming back so I'd love to see it work, uh, randomly. Thanks!

**Comment by r00k** [comment]
Thanks for the feedback @mblayman!

I've opened a PR to change this. Assuming @chrishunt signs off, I'll get this merged and we'll get on with the randomness.

**Comment by mblayman** [comment]
Awesome! Thanks for the fast response.

**Comment by r00k** [comment]
This is merged and deployed.

Enjoy your new, random entry selection!
